### ISSUE TITLE
Bug in sinewave example file

### ISSUE THREAD

**Issue by Tann10** [Carlton941/PyHTM#1]
I was trying to execute sinewave file to see how the algorithm works. I am getting following error:

Traceback (most recent call last):

  File "<ipython-input-349-6990ce46f49a>", line 232, in <module>
    sp, enc = Basic_SP_Example()

  File "<ipython-input-349-6990ce46f49a>", line 66, in Basic_SP_Example
    perm_decrement=perm_dec)

TypeError: __init__() got an unexpected keyword argument 'input_dim'

**Comment by Carlton941** [comment]
Thanks for letting me know, I will fix this ASAP

**Comment by Carlton941** [comment]
Issue should be fixed now. Let me know if you still run into problems!

**Comment by Tann10** [comment]
Great, thank you so much for fixing it!
